name: Publish

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - updates
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main


jobs:
  publish:
    runs-on: ubuntu-latest

    steps: 
      - uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with: 
          dotnet-version: '8.0.x'

      - name: Restore
        run: dotnet restore ./AirMap.sln

      - name: Build
        run: dotnet build ./AirMap.sln --configuration Release --no-restore

      #Add tests here
      #- name: Tests
      #  run: dotnet test ./AirMap.sln --configuration Release --no-restore

      - name: Publish
        if: github.ref == 'refs/heads/main'
        run: dotnet publish ./AirMap.sln --configuration Release --no-build --output '${{ secrets.AZURE_WEBAPP_PACKAGE_PATH }}'

      - name: Deploy
        if: github.ref == 'refs/heads/main'
        uses: azure/webapps-deploy@v2
        with:
            app-name: ${{ secrets.AZURE_WEBAPP_NAME }}
            publish-profile:  ${{ secrets.AZURE_PUBLISH_PROFILE }}
            package: "${{ secrets.AZURE_WEBAPP_PACKAGE_PATH }}"
